# -*- coding: utf-8 -*-
"""Zaliczonko.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AWJ-WXALSt5fQGpxOhtfAPx48vJeucQL
"""

# Commented out IPython magic to ensure Python compatibility.
# 1. INSTALACJA I IMPORTY

!pip install -q albumentations

import os
import zipfile
import copy
import numpy as np
import matplotlib.pyplot as plt
import cv2
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
from torch.utils.tensorboard import SummaryWriter
import albumentations as A
from albumentations.pytorch import ToTensorV2

# Aktywacja/Przeładowanie TensorBoard w Colabie
# %reload_ext tensorboard

# 2. GLOBALNA KONFIGURACJA ŚCIEŻEK (DYNAMICZNY SKANER)

zip_path = '/content/intel_image_classification.zip'
extract_path = '/content/intel_data'

# Rozpakowywanie tylko jeśli folder jeszcze nie istnieje
if not os.path.exists(extract_path):
    print("Rozpakowywanie archiwum...")
    with zipfile.ZipFile(zip_path, 'r') as zip_ref:
        zip_ref.extractall(extract_path)
    print("Dane zostały rozpakowane!")

# Inteligentne, dynamiczne szukanie folderów seg_train i seg_test
found_train = None
found_test = None

for root, dirs, files in os.walk(extract_path):
    # Szukamy folderu seg_train, upewniając się, że to ten właściwy
    if 'seg_train' in dirs:
        potential_path = os.path.join(root, 'seg_train')
        # Zabezpieczenie: sprawdźmy czy w środku nie ma kolejnego seg_train
        if 'seg_train' in os.listdir(potential_path):
            found_train = os.path.join(potential_path, 'seg_train')
        else:
            found_train = potential_path

    if 'seg_test' in dirs:
        potential_path = os.path.join(root, 'seg_test')
        if 'seg_test' in os.listdir(potential_path):
            found_test = os.path.join(potential_path, 'seg_test')
        else:
            found_test = potential_path

if found_train is None or found_test is None:
    raise FileNotFoundError("Nie można odnaleźć folderów 'seg_train' lub 'seg_test' wewnątrz rozpakowanego archiwum! Upewnij się, że plik zip jest poprawny.")

TRAIN_DIR = found_train
TEST_DIR = found_test

print(f"-> Automatycznie wykryta ścieżka TRAIN: {TRAIN_DIR}")
print(f"-> Automatycznie wykryta ścieżka TEST: {TEST_DIR}")

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Używane urządzenie: {device}")

# Pobranie nazw klas i mapowanie na indeksy
class_names = sorted(os.listdir(TRAIN_DIR))
class_to_idx = {cls: i for i, cls in enumerate(class_names)}
print(f"Wykryte klasy ({len(class_names)}): {class_names}")

# 3. NALADOWANIE DANYCH Z ALBUMENTATIONS

class IntelDataset(Dataset):
    def __init__(self, root_dir, class_to_idx, transform=None):
        self.root_dir = root_dir
        self.transform = transform
        self.images = []
        self.labels = []

        for cls_name, cls_idx in class_to_idx.items():
            cls_folder = os.path.join(root_dir, cls_name)
            if not os.path.isdir(cls_folder): continue
            for img_name in os.listdir(cls_folder):
                if img_name.lower().endswith(('.png', '.jpg', '.jpeg')):
                    self.images.append(os.path.join(cls_folder, img_name))
                    self.labels.append(cls_idx)

    def __len__(self):
        return len(self.images)

    def __getitem__(self, idx):
        img_path = self.images[idx]
        image = cv2.imread(img_path)
        image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
        label = self.labels[idx]

        if self.transform:
            augmented = self.transform(image=image)
            image = augmented['image']

        return image, label

# Definicje transformacji i augmentacji
def get_transforms(img_size):
    train_transform = A.Compose([
        A.Resize(img_size[0], img_size[1]),
        A.HorizontalFlip(p=0.5),
        A.RandomBrightnessContrast(p=0.2),
        A.ShiftScaleRotate(shift_limit=0.05, scale_limit=0.05, rotate_limit=15, p=0.5),
        A.CoarseDropout(max_holes=8, max_height=24, max_width=24, p=0.3),
        A.Normalize(mean=(0.485, 0.456, 0.406), std=(0.229, 0.224, 0.225)),
        ToTensorV2(),
    ])

    test_transform = A.Compose([
        A.Resize(img_size[0], img_size[1]),
        A.Normalize(mean=(0.485, 0.456, 0.406), std=(0.229, 0.224, 0.225)),
        ToTensorV2(),
    ])
    return train_transform, test_transform

# 4. ARCHITEKTURA MODELU CNN

class ConfigurableCNN(nn.Module):
    def __init__(self, num_classes=6, activation_type="relu", dropout_rate=0.5):
        super(ConfigurableCNN, self).__init__()

        if activation_type.lower() == "leaky_relu":
            self.act = nn.LeakyReLU(0.1)
        else:
            self.act = nn.ReLU()

        self.conv1 = nn.Conv2d(3, 32, kernel_size=3, padding=1)
        self.bn1 = nn.BatchNorm2d(32)
        self.pool1 = nn.MaxPool2d(2, 2)

        self.conv2 = nn.Conv2d(32, 64, kernel_size=3, padding=1)
        self.bn2 = nn.BatchNorm2d(64)
        self.pool2 = nn.MaxPool2d(2, 2)

        self.conv3 = nn.Conv2d(64, 128, kernel_size=3, padding=1)
        self.bn3 = nn.BatchNorm2d(128)
        self.pool3 = nn.MaxPool2d(2, 2)

        self.gap = nn.AdaptiveAvgPool2d((1, 1))
        self.fc1 = nn.Linear(128, 256)
        self.dropout = nn.Dropout(dropout_rate)
        self.fc2 = nn.Linear(256, num_classes)

    def forward(self, x):
        x_conv1 = self.act(self.bn1(self.conv1(x)))
        x = self.pool1(x_conv1)

        x = self.pool2(self.act(self.bn2(self.conv2(x))))
        x = self.pool3(self.act(self.bn3(self.conv3(x))))

        x = self.gap(x)
        x = x.view(x.size(0), -1)

        x = self.act(self.fc1(x))
        x = self.dropout(x)
        x = self.fc2(x)
        return x, x_conv1

# 5. UNIWERSALNA PĘTLA TRENINGOWA

def train_config_model(config, exp_name):
    print(f"\n⚡ Uruchamiam eksperyment: {exp_name}")
    print(f"Parametry: {config}")

    train_tr, test_tr = get_transforms(config["image_size"])
    train_dataset = IntelDataset(TRAIN_DIR, class_to_idx, transform=train_tr)
    test_dataset = IntelDataset(TEST_DIR, class_to_idx, transform=test_tr)

    train_loader = DataLoader(train_dataset, batch_size=config["batch_size"], shuffle=True, num_workers=2)
    test_loader = DataLoader(test_dataset, batch_size=config["batch_size"], shuffle=False, num_workers=2)

    model = ConfigurableCNN(num_classes=6, activation_type=config["activation"]).to(device)
    criterion = nn.CrossEntropyLoss()

    if config["optimizer"].lower() == "adam":
        optimizer = optim.Adam(model.parameters(), lr=config["learning_rate"])
    else:
        optimizer = optim.SGD(model.parameters(), lr=config["learning_rate"], momentum=0.9)

    writer = SummaryWriter(f'runs/{exp_name}')
    best_acc = 0.0
    best_model_wts = copy.deepcopy(model.state_dict())

    for epoch in range(config["epochs"]):
        # Trening
        model.train()
        running_loss, running_corrects = 0.0, 0
        for inputs, labels in train_loader:
            inputs, labels = inputs.to(device), labels.to(device)
            optimizer.zero_grad()
            outputs, _ = model(inputs)
            _, preds = torch.max(outputs, 1)
            loss = criterion(outputs, labels)
            loss.backward()
            optimizer.step()
            running_loss += loss.item() * inputs.size(0)
            running_corrects += torch.sum(preds == labels.data)

        epoch_loss = running_loss / len(train_loader.dataset)
        epoch_acc = running_corrects.double() / len(train_loader.dataset)

        # Walidacja
        model.eval()
        val_loss, val_corrects = 0.0, 0
        with torch.no_grad():
            for inputs, labels in test_loader:
                inputs, labels = inputs.to(device), labels.to(device)
                outputs, _ = model(inputs)
                _, preds = torch.max(outputs, 1)
                loss = criterion(outputs, labels)
                val_loss += loss.item() * inputs.size(0)
                val_corrects += torch.sum(preds == labels.data)

        val_epoch_loss = val_loss / len(test_loader.dataset)
        val_epoch_acc = val_corrects.double() / len(test_loader.dataset)

        # Zapis do TensorBoard
        writer.add_scalar('Loss/Train', epoch_loss, epoch)
        writer.add_scalar('Accuracy/Train', epoch_acc, epoch)
        writer.add_scalar('Loss/Test', val_epoch_loss, epoch)
        writer.add_scalar('Accuracy/Test', val_epoch_acc, epoch)

        print(f"Epoka {epoch+1}/{config['epochs']} -> Train Acc: {epoch_acc:.4f} | Test Acc: {val_epoch_acc:.4f}")

        if val_epoch_acc > best_acc:
            best_acc = val_epoch_acc
            best_model_wts = copy.deepcopy(model.state_dict())

    writer.close()
    model.load_state_dict(best_model_wts)
    return model, test_loader

# 6. DEFINICJA PARAMETRÓW EKSPERYMENTÓW (CONFIGS)

CONFIG_EXP1 = {
    "image_size": (150, 150),
    "batch_size": 32,
    "learning_rate": 1e-3,
    "epochs": 5,
    "optimizer": "adam",
    "activation": "relu"
}

CONFIG_EXP2 = {
    "image_size": (150, 150),
    "batch_size": 64,
    "learning_rate": 1e-4,
    "epochs": 5,
    "optimizer": "adam",
    "activation": "relu"
}

CONFIG_EXP3 = {
    "image_size": (150, 150),
    "batch_size": 32,
    "learning_rate": 1e-3,
    "epochs": 5,
    "optimizer": "sgd",
    "activation": "leaky_relu"
}

# SEKWENCYJNE URUCHOMIENIE AUTOMATU TESTOWEGO
model_1, loader_1 = train_config_model(CONFIG_EXP1, "Exp1_Baseline_Adam")
model_2, _        = train_config_model(CONFIG_EXP2, "Exp2_HighBatch_LowLR")
model_3, _        = train_config_model(CONFIG_EXP3, "Exp3_SGD_LeakyReLU")

# 7. URUCHOMIENIE TENSORBOARD W COLABIE

# %tensorboard --logdir runs

# 8. EWALUACJA: MAPY CECH (FEATURE MAPS) I BŁĘDY

def visualize_results(model, test_loader):
    model.eval()
    with torch.no_grad():
        for inputs, labels in test_loader:
            inputs, labels = inputs.to(device), labels.to(device)
            outputs, feature_maps = model(inputs)
            _, preds = torch.max(outputs, 1)

            for i in range(inputs.size(0)):
                if preds[i] != labels[i]:
                    img_np = inputs[i].cpu().numpy().transpose((1, 2, 0))
                    f_map = feature_maps[i].cpu().numpy()
                    f_map_avg = np.mean(f_map, axis=0)

                    fig, axes = plt.subplots(1, 2, figsize=(10, 5))
                    axes[0].imshow(np.clip(img_np * 0.229 + 0.485, 0, 1))
                    axes[0].set_title(f"Prawda: {class_names[labels[i]]}\nPredykcja: {class_names[preds[i]]}")
                    axes[0].axis('off')

                    axes[1].imshow(f_map_avg, cmap='viridis')
                    axes[1].set_title("Mapa cech (Warstwa Conv1)")
                    axes[1].axis('off')

                    plt.show()
                    return

print("\nWizualizacja map cech oraz błędnej próbki dla Modelu 1:")
visualize_results(model_1, loader_1)